### ISSUE TITLE
When can we expect the multimodal model to be released?

### ISSUE THREAD

**Issue by ninjasaid2k** [Picsart-AI-Research/PAIR-Diffusion#1]

**Comment by vidit98** [comment]
Hi, thanks for your interest in our work. We have released the inference code. In the next few days, we will also release the training scripts.

**Comment by TruthSearcher** [comment]
I want to know when the new model will be released, it looks interesting 👀

**Comment by vidit98** [comment]
Thanks for your interest. We have released the model.
